# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: psip-jar
        path: target/psip-*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Copy artifact
      run: cp target/psip-*.jar target/psip-${{ github.run_number }}.jar
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: psip
        environment_name: Psip-env-java
        version_label: ${{ github.run_number }}
        region: us-east-2
        deployment_package: target/psip-${{ github.run_number }}.jar
